// Server-side replacement for `varlock/env`.
//
// Aliased into the Nitro server bundle via `nitro.alias` in
// `vite.config.ts`. The client bundle is NOT affected: the varlock
// vite plugin's build-time static replacer inlines `@public` values
// there at build time, so the browser never reaches this shim.
//
// Why this exists:
//
// Under the current combination of Vite 8 + TanStack Start 1.167.16
// + Nitro v3 + rolldown, the bundled `_libs/varlock.mjs` chunk's
// `var ENV = new Proxy(...)` assignment does not run before other
// server modules that import `ENV` are evaluated — so `ENV` is
// literally `undefined` at runtime on every `ENV.X` access. The
// failure mode is reproducible on the Coolify deploy host but not
// on local docker builds of the exact same commit + lockfile +
// binary digest, which points at a rolldown chunk-ordering
// non-determinism that we have not been able to root-cause.
//
// The upstream bug is the same class as dmno-dev/varlock#516
// (`moduleIds[0]` entry detection in @varlock/vite-integration is
// unstable), but the workaround from that issue
// (`ssrInjectMode: 'auto-load'`) no longer suffices because the
// plugin's transform hook does not fire for the Nitro server entry
// anymore under the current dep graph.
//
// This shim bypasses the broken varlock runtime entirely for the
// server bundle. At runtime, `varlock run --` has already exported
// all resolved env values into `process.env` before execing node
// (see `fullInjectedEnv` in
// `node_modules/varlock/dist/chunk-P4WZ2JXY.js`), and Coolify
// layers its own runtime env vars on top. Reading from
// `process.env` is therefore equivalent to reading from varlock's
// ENV proxy for all non-transforming access.
//
// Caveats:
//
// * Values are strings (or undefined). Any `@type=port` or other
//   varlock coercion that happened at the schema layer is applied
//   at `varlock run` time when values are serialized back to
//   `process.env`, so downstream code that expected numbers will
//   still need to parse them. We have not observed this in the
//   current codebase, but if varlock is ever asked to coerce to
//   non-string types and a consumer relies on that at runtime,
//   this shim will silently return a string.
// * Type safety is preserved via `src/env.d.ts`, which is
//   generated by `varlock typegen` and declares the shape of
//   `ENV`. Import consumers keep their type hints.

type EnvShape = Record<string, string | undefined>;

export const ENV: EnvShape = new Proxy({} as EnvShape, {
  get(_target, prop): string | undefined {
    if (typeof prop === 'symbol') return undefined;
    return process.env[prop];
  },
  has(_target, prop): boolean {
    if (typeof prop === 'symbol') return false;
    return prop in process.env;
  },
});
