name: Setup Node and pnpm
description: Install Node from .nvmrc and pnpm from package.json, with pnpm cache.

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      with:
        run_install: false

    - name: Setup Node
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version-file: .nvmrc
        cache: pnpm

    - name: Restore TypeScript incremental cache
      uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
      with:
        path: node_modules/.cache/typescript/tsbuildinfo
        key: tsbuildinfo-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml', 'tsconfig.json') }}
        restore-keys: |
          tsbuildinfo-${{ runner.os }}-

    - name: Restore ESLint cache
      uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
      with:
        path: node_modules/.cache/eslint/.eslintcache
        key: eslintcache-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml', 'eslint.config.js') }}
        restore-keys: |
          eslintcache-${{ runner.os }}-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
