onlyBuiltDependencies:
  - esbuild
  - lefthook
  - msw
  - unrs-resolver

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  hono@<4.11.10: '>=4.11.10'
  hono@<4.11.7: '>=4.11.7'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  minimatch@<10.2.1: '>=10.2.2'
