import {
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  BellIcon,
  CalendarIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleCheckIcon,
  CircleIcon,
  CreditCardIcon,
  ExternalLinkIcon,
  EyeIcon,
  EyeOffIcon,
  FilterIcon,
  HomeIcon,
  InfoIcon,
  Loader2Icon,
  LogOutIcon,
  MailIcon,
  MinusIcon,
  MoonIcon,
  MoreHorizontalIcon,
  OctagonXIcon,
  PanelLeftIcon,
  PlusIcon,
  RefreshCwIcon,
  SearchIcon,
  SettingsIcon,
  SunIcon,
  Trash2Icon,
  TriangleAlertIcon,
  UserIcon,
  XIcon,
} from 'lucide-react';

type IconComponent = typeof SunIcon;

const Icons = {
  ArrowDown: ArrowDownIcon,
  ArrowLeft: ArrowLeftIcon,
  ArrowRight: ArrowRightIcon,
  ArrowUp: ArrowUpIcon,
  Bell: BellIcon,
  Calendar: CalendarIcon,
  Check: CheckIcon,
  ChevronDown: ChevronDownIcon,
  ChevronLeft: ChevronLeftIcon,
  ChevronRight: ChevronRightIcon,
  ChevronUp: ChevronUpIcon,
  Circle: CircleIcon,
  CircleCheck: CircleCheckIcon,
  CreditCard: CreditCardIcon,
  ExternalLink: ExternalLinkIcon,
  Eye: EyeIcon,
  EyeOff: EyeOffIcon,
  Filter: FilterIcon,
  Home: HomeIcon,
  Info: InfoIcon,
  Loader2: Loader2Icon,
  LogOut: LogOutIcon,
  Mail: MailIcon,
  Minus: MinusIcon,
  Moon: MoonIcon,
  MoreHorizontal: MoreHorizontalIcon,
  OctagonX: OctagonXIcon,
  PanelLeft: PanelLeftIcon,
  Plus: PlusIcon,
  RefreshCw: RefreshCwIcon,
  Search: SearchIcon,
  Settings: SettingsIcon,
  Sun: SunIcon,
  Trash2: Trash2Icon,
  TriangleAlert: TriangleAlertIcon,
  User: UserIcon,
  X: XIcon,
} as const;

export { type IconComponent, Icons };
