import {
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowLeftToLineIcon,
  ArrowRightIcon,
  ArrowRightToLineIcon,
  ArrowUpIcon,
  BellIcon,
  CalendarIcon,
  CameraIcon,
  ChartBarIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronsUpDownIcon,
  ChevronUpIcon,
  CircleCheckIcon,
  CircleHelpIcon,
  CircleIcon,
  CircleUserRoundIcon,
  CommandIcon,
  CornerUpLeftIcon,
  CornerUpRightIcon,
  CreditCardIcon,
  DatabaseIcon,
  EllipsisVerticalIcon,
  ExternalLinkIcon,
  EyeIcon,
  EyeOffIcon,
  FileChartColumnIcon,
  FileIcon,
  FileTextIcon,
  FilterIcon,
  FolderIcon,
  GlobeIcon,
  GripHorizontalIcon,
  GripVerticalIcon,
  HomeIcon,
  InfoIcon,
  LayoutDashboardIcon,
  ListIcon,
  Loader2Icon,
  LogOutIcon,
  MailIcon,
  MinusIcon,
  MoonIcon,
  MoreHorizontalIcon,
  OctagonXIcon,
  PanelLeftIcon,
  PinOffIcon,
  PlusIcon,
  RefreshCwIcon,
  SearchIcon,
  Settings2Icon,
  SettingsIcon,
  ShareIcon,
  StarIcon,
  SunIcon,
  Trash2Icon,
  TriangleAlertIcon,
  UserIcon,
  UsersIcon,
  XIcon,
} from 'lucide-react';

type IconComponent = typeof SunIcon;

const Icons = {
  ArrowDown: ArrowDownIcon,
  ArrowLeft: ArrowLeftIcon,
  ArrowLeftToLine: ArrowLeftToLineIcon,
  ArrowRight: ArrowRightIcon,
  ArrowRightToLine: ArrowRightToLineIcon,
  ArrowUp: ArrowUpIcon,
  Bell: BellIcon,
  Calendar: CalendarIcon,
  Camera: CameraIcon,
  ChartBar: ChartBarIcon,
  Check: CheckIcon,
  ChevronDown: ChevronDownIcon,
  ChevronLeft: ChevronLeftIcon,
  ChevronRight: ChevronRightIcon,
  ChevronsUpDown: ChevronsUpDownIcon,
  ChevronUp: ChevronUpIcon,
  Circle: CircleIcon,
  CircleCheck: CircleCheckIcon,
  CircleHelp: CircleHelpIcon,
  CircleUserRound: CircleUserRoundIcon,
  Command: CommandIcon,
  CornerUpLeft: CornerUpLeftIcon,
  CornerUpRight: CornerUpRightIcon,
  CreditCard: CreditCardIcon,
  Database: DatabaseIcon,
  EllipsisVertical: EllipsisVerticalIcon,
  ExternalLink: ExternalLinkIcon,
  Eye: EyeIcon,
  EyeOff: EyeOffIcon,
  File: FileIcon,
  FileChartColumn: FileChartColumnIcon,
  FileText: FileTextIcon,
  Filter: FilterIcon,
  Folder: FolderIcon,
  Globe: GlobeIcon,
  GripHorizontal: GripHorizontalIcon,
  GripVertical: GripVerticalIcon,
  Home: HomeIcon,
  Info: InfoIcon,
  LayoutDashboard: LayoutDashboardIcon,
  List: ListIcon,
  Loader2: Loader2Icon,
  LogOut: LogOutIcon,
  Mail: MailIcon,
  Minus: MinusIcon,
  Moon: MoonIcon,
  MoreHorizontal: MoreHorizontalIcon,
  OctagonX: OctagonXIcon,
  PanelLeft: PanelLeftIcon,
  PinOff: PinOffIcon,
  Plus: PlusIcon,
  RefreshCw: RefreshCwIcon,
  Search: SearchIcon,
  Settings: SettingsIcon,
  Settings2: Settings2Icon,
  Share: ShareIcon,
  Star: StarIcon,
  Sun: SunIcon,
  Trash2: Trash2Icon,
  TriangleAlert: TriangleAlertIcon,
  User: UserIcon,
  Users: UsersIcon,
  X: XIcon,
} as const;

export { type IconComponent, Icons };
