/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as DemoRouteRouteImport } from './routes/_demo/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as DemoDashboardRouteImport } from './routes/demo/dashboard'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCategoriesRouteImport } from './routes/_app/categories'
import { Route as AppAccountsRouteImport } from './routes/_app/accounts'
import { Route as DemoComponentsRouteRouteImport } from './routes/_demo/components/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DemoComponentsSelectionsRouteImport } from './routes/_demo/components/selections'
import { Route as DemoComponentsLayoutRouteImport } from './routes/_demo/components/layout'
import { Route as DemoComponentsFormsRouteImport } from './routes/_demo/components/forms'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRouteRoute = DemoRouteRouteImport.update({
  id: '/_demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/demo/drizzle',
  path: '/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDashboardRoute = DemoDashboardRouteImport.update({
  id: '/demo/dashboard',
  path: '/demo/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRouteRoute,
} as any)
const DemoComponentsRouteRoute = DemoComponentsRouteRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => DemoRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoComponentsSelectionsRoute =
  DemoComponentsSelectionsRouteImport.update({
    id: '/selections',
    path: '/selections',
    getParentRoute: () => DemoComponentsRouteRoute,
  } as any)
const DemoComponentsLayoutRoute = DemoComponentsLayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => DemoComponentsRouteRoute,
} as any)
const DemoComponentsFormsRoute = DemoComponentsFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => DemoComponentsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/components': typeof DemoComponentsRouteRouteWithChildren
  '/accounts': typeof AppAccountsRoute
  '/categories': typeof AppCategoriesRoute
  '/dashboard': typeof AppDashboardRoute
  '/transactions': typeof AppTransactionsRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/components/forms': typeof DemoComponentsFormsRoute
  '/components/layout': typeof DemoComponentsLayoutRoute
  '/components/selections': typeof DemoComponentsSelectionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/components': typeof DemoComponentsRouteRouteWithChildren
  '/accounts': typeof AppAccountsRoute
  '/categories': typeof AppCategoriesRoute
  '/dashboard': typeof AppDashboardRoute
  '/transactions': typeof AppTransactionsRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/components/forms': typeof DemoComponentsFormsRoute
  '/components/layout': typeof DemoComponentsLayoutRoute
  '/components/selections': typeof DemoComponentsSelectionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_demo': typeof DemoRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_demo/components': typeof DemoComponentsRouteRouteWithChildren
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/_public/': typeof PublicIndexRoute
  '/_demo/components/forms': typeof DemoComponentsFormsRoute
  '/_demo/components/layout': typeof DemoComponentsLayoutRoute
  '/_demo/components/selections': typeof DemoComponentsSelectionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/accounts'
    | '/categories'
    | '/dashboard'
    | '/transactions'
    | '/sign-in'
    | '/sign-up'
    | '/demo/better-auth'
    | '/demo/dashboard'
    | '/demo/drizzle'
    | '/components/forms'
    | '/components/layout'
    | '/components/selections'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components'
    | '/accounts'
    | '/categories'
    | '/dashboard'
    | '/transactions'
    | '/sign-in'
    | '/sign-up'
    | '/demo/better-auth'
    | '/demo/dashboard'
    | '/demo/drizzle'
    | '/components/forms'
    | '/components/layout'
    | '/components/selections'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_demo'
    | '/_public'
    | '/_demo/components'
    | '/_app/accounts'
    | '/_app/categories'
    | '/_app/dashboard'
    | '/_app/transactions'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/demo/better-auth'
    | '/demo/dashboard'
    | '/demo/drizzle'
    | '/_public/'
    | '/_demo/components/forms'
    | '/_demo/components/layout'
    | '/_demo/components/selections'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DemoRouteRoute: typeof DemoRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoDashboardRoute: typeof DemoDashboardRoute
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_demo': {
      id: '/_demo'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DemoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/demo/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/dashboard': {
      id: '/demo/dashboard'
      path: '/demo/dashboard'
      fullPath: '/demo/dashboard'
      preLoaderRoute: typeof DemoDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_demo/components': {
      id: '/_demo/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof DemoComponentsRouteRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_demo/components/selections': {
      id: '/_demo/components/selections'
      path: '/selections'
      fullPath: '/components/selections'
      preLoaderRoute: typeof DemoComponentsSelectionsRouteImport
      parentRoute: typeof DemoComponentsRouteRoute
    }
    '/_demo/components/layout': {
      id: '/_demo/components/layout'
      path: '/layout'
      fullPath: '/components/layout'
      preLoaderRoute: typeof DemoComponentsLayoutRouteImport
      parentRoute: typeof DemoComponentsRouteRoute
    }
    '/_demo/components/forms': {
      id: '/_demo/components/forms'
      path: '/forms'
      fullPath: '/components/forms'
      preLoaderRoute: typeof DemoComponentsFormsRouteImport
      parentRoute: typeof DemoComponentsRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppTransactionsRoute: AppTransactionsRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DemoComponentsRouteRouteChildren {
  DemoComponentsFormsRoute: typeof DemoComponentsFormsRoute
  DemoComponentsLayoutRoute: typeof DemoComponentsLayoutRoute
  DemoComponentsSelectionsRoute: typeof DemoComponentsSelectionsRoute
}

const DemoComponentsRouteRouteChildren: DemoComponentsRouteRouteChildren = {
  DemoComponentsFormsRoute: DemoComponentsFormsRoute,
  DemoComponentsLayoutRoute: DemoComponentsLayoutRoute,
  DemoComponentsSelectionsRoute: DemoComponentsSelectionsRoute,
}

const DemoComponentsRouteRouteWithChildren =
  DemoComponentsRouteRoute._addFileChildren(DemoComponentsRouteRouteChildren)

interface DemoRouteRouteChildren {
  DemoComponentsRouteRoute: typeof DemoComponentsRouteRouteWithChildren
}

const DemoRouteRouteChildren: DemoRouteRouteChildren = {
  DemoComponentsRouteRoute: DemoComponentsRouteRouteWithChildren,
}

const DemoRouteRouteWithChildren = DemoRouteRoute._addFileChildren(
  DemoRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DemoRouteRoute: DemoRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoDashboardRoute: DemoDashboardRoute,
  DemoDrizzleRoute: DemoDrizzleRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
