/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as DemoRouteRouteImport } from './routes/_demo/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as AppImportsRouteImport } from './routes/_app/imports'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCategoriesRouteImport } from './routes/_app/categories'
import { Route as AppBudgetsRouteImport } from './routes/_app/budgets'
import { Route as AppAccountsRouteImport } from './routes/_app/accounts'
import { Route as DemoComponentsRouteRouteImport } from './routes/_demo/components/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DemoComponentsSelectionsRouteImport } from './routes/_demo/components/selections'
import { Route as DemoComponentsOverlaysRouteImport } from './routes/_demo/components/overlays'
import { Route as DemoComponentsNavigationRouteImport } from './routes/_demo/components/navigation'
import { Route as DemoComponentsLayoutRouteImport } from './routes/_demo/components/layout'
import { Route as DemoComponentsFormsRouteImport } from './routes/_demo/components/forms'
import { Route as DemoComponentsDateRouteImport } from './routes/_demo/components/date'
import { Route as DemoComponentsDataRouteImport } from './routes/_demo/components/data'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRouteRoute = DemoRouteRouteImport.update({
  id: '/_demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppImportsRoute = AppImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBudgetsRoute = AppBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRouteRoute,
} as any)
const DemoComponentsRouteRoute = DemoComponentsRouteRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => DemoRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoComponentsSelectionsRoute =
  DemoComponentsSelectionsRouteImport.update({
    id: '/selections',
    path: '/selections',
    getParentRoute: () => DemoComponentsRouteRoute,
  } as any)
const DemoComponentsOverlaysRoute = DemoComponentsOverlaysRouteImport.update({
  id: '/overlays',
  path: '/overlays',
  getParentRoute: () => DemoComponentsRouteRoute,
} as any)
const DemoComponentsNavigationRoute =
  DemoComponentsNavigationRouteImport.update({
    id: '/navigation',
    path: '/navigation',
    getParentRoute: () => DemoComponentsRouteRoute,
  } as any)
const DemoComponentsLayoutRoute = DemoComponentsLayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => DemoComponentsRouteRoute,
} as any)
const DemoComponentsFormsRoute = DemoComponentsFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => DemoComponentsRouteRoute,
} as any)
const DemoComponentsDateRoute = DemoComponentsDateRouteImport.update({
  id: '/date',
  path: '/date',
  getParentRoute: () => DemoComponentsRouteRoute,
} as any)
const DemoComponentsDataRoute = DemoComponentsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => DemoComponentsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/components': typeof DemoComponentsRouteRouteWithChildren
  '/accounts': typeof AppAccountsRoute
  '/budgets': typeof AppBudgetsRoute
  '/categories': typeof AppCategoriesRoute
  '/dashboard': typeof AppDashboardRoute
  '/imports': typeof AppImportsRoute
  '/transactions': typeof AppTransactionsRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/components/data': typeof DemoComponentsDataRoute
  '/components/date': typeof DemoComponentsDateRoute
  '/components/forms': typeof DemoComponentsFormsRoute
  '/components/layout': typeof DemoComponentsLayoutRoute
  '/components/navigation': typeof DemoComponentsNavigationRoute
  '/components/overlays': typeof DemoComponentsOverlaysRoute
  '/components/selections': typeof DemoComponentsSelectionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/components': typeof DemoComponentsRouteRouteWithChildren
  '/accounts': typeof AppAccountsRoute
  '/budgets': typeof AppBudgetsRoute
  '/categories': typeof AppCategoriesRoute
  '/dashboard': typeof AppDashboardRoute
  '/imports': typeof AppImportsRoute
  '/transactions': typeof AppTransactionsRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/components/data': typeof DemoComponentsDataRoute
  '/components/date': typeof DemoComponentsDateRoute
  '/components/forms': typeof DemoComponentsFormsRoute
  '/components/layout': typeof DemoComponentsLayoutRoute
  '/components/navigation': typeof DemoComponentsNavigationRoute
  '/components/overlays': typeof DemoComponentsOverlaysRoute
  '/components/selections': typeof DemoComponentsSelectionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_demo': typeof DemoRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_demo/components': typeof DemoComponentsRouteRouteWithChildren
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/budgets': typeof AppBudgetsRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/imports': typeof AppImportsRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_public/': typeof PublicIndexRoute
  '/_demo/components/data': typeof DemoComponentsDataRoute
  '/_demo/components/date': typeof DemoComponentsDateRoute
  '/_demo/components/forms': typeof DemoComponentsFormsRoute
  '/_demo/components/layout': typeof DemoComponentsLayoutRoute
  '/_demo/components/navigation': typeof DemoComponentsNavigationRoute
  '/_demo/components/overlays': typeof DemoComponentsOverlaysRoute
  '/_demo/components/selections': typeof DemoComponentsSelectionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/accounts'
    | '/budgets'
    | '/categories'
    | '/dashboard'
    | '/imports'
    | '/transactions'
    | '/sign-in'
    | '/sign-up'
    | '/components/data'
    | '/components/date'
    | '/components/forms'
    | '/components/layout'
    | '/components/navigation'
    | '/components/overlays'
    | '/components/selections'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components'
    | '/accounts'
    | '/budgets'
    | '/categories'
    | '/dashboard'
    | '/imports'
    | '/transactions'
    | '/sign-in'
    | '/sign-up'
    | '/components/data'
    | '/components/date'
    | '/components/forms'
    | '/components/layout'
    | '/components/navigation'
    | '/components/overlays'
    | '/components/selections'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_demo'
    | '/_public'
    | '/_demo/components'
    | '/_app/accounts'
    | '/_app/budgets'
    | '/_app/categories'
    | '/_app/dashboard'
    | '/_app/imports'
    | '/_app/transactions'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_public/'
    | '/_demo/components/data'
    | '/_demo/components/date'
    | '/_demo/components/forms'
    | '/_demo/components/layout'
    | '/_demo/components/navigation'
    | '/_demo/components/overlays'
    | '/_demo/components/selections'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DemoRouteRoute: typeof DemoRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_demo': {
      id: '/_demo'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DemoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/imports': {
      id: '/_app/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof AppImportsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/budgets': {
      id: '/_app/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AppBudgetsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_demo/components': {
      id: '/_demo/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof DemoComponentsRouteRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_demo/components/selections': {
      id: '/_demo/components/selections'
      path: '/selections'
      fullPath: '/components/selections'
      preLoaderRoute: typeof DemoComponentsSelectionsRouteImport
      parentRoute: typeof DemoComponentsRouteRoute
    }
    '/_demo/components/overlays': {
      id: '/_demo/components/overlays'
      path: '/overlays'
      fullPath: '/components/overlays'
      preLoaderRoute: typeof DemoComponentsOverlaysRouteImport
      parentRoute: typeof DemoComponentsRouteRoute
    }
    '/_demo/components/navigation': {
      id: '/_demo/components/navigation'
      path: '/navigation'
      fullPath: '/components/navigation'
      preLoaderRoute: typeof DemoComponentsNavigationRouteImport
      parentRoute: typeof DemoComponentsRouteRoute
    }
    '/_demo/components/layout': {
      id: '/_demo/components/layout'
      path: '/layout'
      fullPath: '/components/layout'
      preLoaderRoute: typeof DemoComponentsLayoutRouteImport
      parentRoute: typeof DemoComponentsRouteRoute
    }
    '/_demo/components/forms': {
      id: '/_demo/components/forms'
      path: '/forms'
      fullPath: '/components/forms'
      preLoaderRoute: typeof DemoComponentsFormsRouteImport
      parentRoute: typeof DemoComponentsRouteRoute
    }
    '/_demo/components/date': {
      id: '/_demo/components/date'
      path: '/date'
      fullPath: '/components/date'
      preLoaderRoute: typeof DemoComponentsDateRouteImport
      parentRoute: typeof DemoComponentsRouteRoute
    }
    '/_demo/components/data': {
      id: '/_demo/components/data'
      path: '/data'
      fullPath: '/components/data'
      preLoaderRoute: typeof DemoComponentsDataRouteImport
      parentRoute: typeof DemoComponentsRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppBudgetsRoute: typeof AppBudgetsRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppImportsRoute: typeof AppImportsRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppBudgetsRoute: AppBudgetsRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppImportsRoute: AppImportsRoute,
  AppTransactionsRoute: AppTransactionsRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DemoComponentsRouteRouteChildren {
  DemoComponentsDataRoute: typeof DemoComponentsDataRoute
  DemoComponentsDateRoute: typeof DemoComponentsDateRoute
  DemoComponentsFormsRoute: typeof DemoComponentsFormsRoute
  DemoComponentsLayoutRoute: typeof DemoComponentsLayoutRoute
  DemoComponentsNavigationRoute: typeof DemoComponentsNavigationRoute
  DemoComponentsOverlaysRoute: typeof DemoComponentsOverlaysRoute
  DemoComponentsSelectionsRoute: typeof DemoComponentsSelectionsRoute
}

const DemoComponentsRouteRouteChildren: DemoComponentsRouteRouteChildren = {
  DemoComponentsDataRoute: DemoComponentsDataRoute,
  DemoComponentsDateRoute: DemoComponentsDateRoute,
  DemoComponentsFormsRoute: DemoComponentsFormsRoute,
  DemoComponentsLayoutRoute: DemoComponentsLayoutRoute,
  DemoComponentsNavigationRoute: DemoComponentsNavigationRoute,
  DemoComponentsOverlaysRoute: DemoComponentsOverlaysRoute,
  DemoComponentsSelectionsRoute: DemoComponentsSelectionsRoute,
}

const DemoComponentsRouteRouteWithChildren =
  DemoComponentsRouteRoute._addFileChildren(DemoComponentsRouteRouteChildren)

interface DemoRouteRouteChildren {
  DemoComponentsRouteRoute: typeof DemoComponentsRouteRouteWithChildren
}

const DemoRouteRouteChildren: DemoRouteRouteChildren = {
  DemoComponentsRouteRoute: DemoComponentsRouteRouteWithChildren,
}

const DemoRouteRouteWithChildren = DemoRouteRoute._addFileChildren(
  DemoRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DemoRouteRoute: DemoRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
